// Tiles Turnt Count
const INCREMENT_COUNT = "INCREMENT_COUNT";
const RESET_COUNT = "RESET_COUNT";

// flaggedLocations
const UPDATE_FLAGGED_LOCATIONS = "UPDATE_FLAGGED_LOCATIONS";
const RESET_FLAGGED_LOCATIONS = "RESET_FLAGGED_LOCATIONS";

// gameOptions
const UPDATE_GRID_OPTIONS = "UPDATE_GRID_OPTIONS";
const RESET_GRID_OPTIONS = "RESET_GRID_OPTIONS";

export default {
  INCREMENT_COUNT,
  RESET_COUNT,
  UPDATE_FLAGGED_LOCATIONS,
  RESET_FLAGGED_LOCATIONS,
  UPDATE_GRID_OPTIONS,
  RESET_GRID_OPTIONS
};
