// Tiles Turnt Count
const INCREMENT_COUNT = "INCREMENT_COUNT";
const RESET_COUNT = "RESET_COUNT";

// flaggedLocations
const UPDATE_FLAGGED_LOCATIONS = "UPDATE_FLAGGED_LOCATIONS";
const RESET_FLAGGED_LOCATIONS = "RESET_FLAGGED_LOCATIONS";

// gameOptions
const UPDATE_GRID_OPTIONS = "UPDATE_GRID_OPTIONS";
const RESET_GRID_OPTIONS = "RESET_GRID_OPTIONS";

// roundLevel
const INCREMENT_ROUND_LEVEL = "INCREMENT_ROUND_LEVEL";
const RESET_ROUND_LEVEL = "RESET_ROUND_LEVEL";

// toggleSound
const TOGGLE_SOUND = "TOGGLE_SOUND";

export default {
  INCREMENT_COUNT,
  RESET_COUNT,
  UPDATE_FLAGGED_LOCATIONS,
  RESET_FLAGGED_LOCATIONS,
  UPDATE_GRID_OPTIONS,
  RESET_GRID_OPTIONS,
  INCREMENT_ROUND_LEVEL,
  RESET_ROUND_LEVEL,
  TOGGLE_SOUND,
};

export interface ActionType {
  type: string;
  payload: object;
}
